[general]
id = "sd-comn"
config_dir = "/etc/scion"

[sd]
address = "0.0.0.0:30255"

[path_db]
connection = "/var/lib/scion/sd.path.db"

[trust_db]
connection = "/var/lib/scion/sd.trust.db"

[log.console]
level = "info"

[metrics]
prometheus = "0.0.0.0:30455"
