[general]
id = "cs-comn"
config_dir = "/etc/scion"

[trust_db]
connection = "/var/lib/scion/cs-comn.trust.db"

[beacon_db]
connection = "/var/lib/scion/cs-comn.beacon.db"

[path_db]
connection = "/var/lib/scion/cs-comn.path.db"

[log.console]
level = "info"

[metrics]
prometheus = "0.0.0.0:30401"
