[general]
id = "cs-core"
config_dir = "/etc/scion"

[trust_db]
connection = "/var/lib/scion/cs-core.trust.db"

[beacon_db]
connection = "/var/lib/scion/cs-core.beacon.db"

[path_db]
connection = "/var/lib/scion/cs-core.path.db"

[log.console]
level = "info"

[metrics]
prometheus = "0.0.0.0:30401"
