[general]
id = "cs-pac"
config_dir = "/etc/scion"

[trust_db]
connection = "/var/lib/scion/cs-pac.trust.db"

[beacon_db]
connection = "/var/lib/scion/cs-pac.beacon.db"

[path_db]
connection = "/var/lib/scion/cs-pac.path.db"

[log.console]
level = "info"

[metrics]
prometheus = "0.0.0.0:30401"
